import { readFileSync, writeFileSync, existsSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const IMAGES_DIR = join(ROOT, 'src', 'images');
const OUTPUT_FILE = join(ROOT, 'src', 'imageData.js');

const EXPECTED = [
  'cardinal',
  'mockingbird',
  'bluejay',
  'carolinawren',
  'scissortail',
  'paintedbunting',
  'robin',
  'bluebird',
  'yellowrumped',
  'barnswallow',
  'purplemartin',
  'grackle',
  'chickadee',
  'titmouse',
  'redtailedhawk',
  'mississippikite',
  'osprey',
  'baldeagle',
  'coopershawk',
  'kestrel',
  'greathorned',
  'barredowl',
  'greatblueheron',
  'greatergret',
  'snowyegret',
  'greenheron',
  'bcnightheron',
  'cormorant',
  'whitepelican',
  'coot',
  'piedbilledgrebe',
  'whitefacedibis',
  'killdeer',
  'bnstilt',
  'avocet',
  'leastsandpiper',
  'redbellied',
  'downy',
  'flicker',
  'beltedkingfisher',
  'chimneyswift',
  'rubythroated',
  'nighthawk',
  'mourningdove',
];

const found = [];
const missing = [];
const entries = {};

for (const key of EXPECTED) {
  const filePath = join(IMAGES_DIR, `${key}.jpg`);
  if (existsSync(filePath)) {
    const data = readFileSync(filePath);
    entries[key] = `data:image/jpeg;base64,${data.toString('base64')}`;
    found.push(key);
  } else {
    entries[key] = '';
    missing.push(key);
  }
}

// Also pick up any extra .jpg files in the directory
if (existsSync(IMAGES_DIR)) {
  for (const file of readdirSync(IMAGES_DIR)) {
    if (file.endsWith('.jpg') || file.endsWith('.jpeg')) {
      const key = file.replace(/\.(jpg|jpeg)$/, '');
      if (!EXPECTED.includes(key)) {
        const data = readFileSync(join(IMAGES_DIR, file));
        entries[key] = `data:image/jpeg;base64,${data.toString('base64')}`;
        console.log(`  + Extra image bundled: ${key}`);
      }
    }
  }
}

const lines = Object.entries(entries).map(
  ([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`
);
const output = `// AUTO-GENERATED by scripts/embed-images.js — do not edit manually
export const images = {\n${lines.join('\n')}\n};\n`;

writeFileSync(OUTPUT_FILE, output, 'utf-8');

console.log('\n=== embed-images ===');
if (found.length > 0) {
  console.log(`Found (${found.length}): ${found.join(', ')}`);
}
if (missing.length > 0) {
  console.warn(`Missing (${missing.length}): ${missing.join(', ')}`);
  console.warn('  Place .jpg files in src/images/ and re-run: npm run embed-images');
}
console.log(`Output: src/imageData.js (${Math.round(output.length / 1024)} KB)`);
if (missing.length === EXPECTED.length) {
  console.warn('\n  WARNING: No images found. Cards will show placeholder boxes.\n');
}
